### ISSUE TITLE
Error Ikhsan

### ISSUE THREAD

**Issue by LunarPatch1St** [bayusamudra5502/Netizener#21]
Error encountered while pushing to the remote repository: Git failed with a fatal error.
ArgumentNullException encountered.
   Value cannot be null.
Parameter name: path
cannot spawn /C/Program Files/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
could not read Username for 'https://github.com': terminal prompts disabled
Pushing to https://github.com/LunarPatch1St/Netizener.git

**Comment by bayusamudra5502** [comment]
Harus manual dan :v
